server:
  port: 8083
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://syh80883.cafe24.com/syh80883
    username: syh80883
    password: abc123!@
    sql-script-encoding: utf-8
  messages:
    basename: messages/messages, messages/error

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri:
            scope:
              - profile
              - email
          naver:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri:
            scope:
              - profile
          kakao:
            client-id: 88776da86f2f10217da7c55c326ba004
            client-secret: 6sv0nU8FByKMWc7FP1j5NMzJdW5iGqYX
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8083/api/oauth/callback/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            unlink-uri: https://accounts.google.com/o/oauth2/revoke
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            unlink-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            unlink-uri: https://kapi.kakao.com/v1/me/unlink

jwt:
  secretKey: testtesttesttesttest42fwef234132412wqdfqwf12
  refreshKey: testtesttesttesttest42fwef234132412wqdfqwf12vvdsvsd
  signatureAlgorithm: HS256
  accessTokenExpired: 604800
  refreshTokenExpired: 6048000

client:
  origins: http://localhost:3000